name: Google To GeoJSON

on:
  schedule:
    - cron: "0 2 * * *" # 每天凌晨2点执行一次
  workflow_dispatch: # 允许手动触发

jobs:
  download_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # 检出代码仓库

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # 设置Python版本

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install shapely requests # 安装所需的Python包

    - name: Download KMZ file
      run: |
        URL="https://www.google.com/maps/d/kml?mid=103ngIYVR56ypc1eJp_4FntEU0Nc&cid=mp&cv=qNGi_t2KHPo.zh_CN"
        OUTPUT_FILE="downloaded_file.kmz"
        curl -o $OUTPUT_FILE $URL # 下载KMZ文件
      shell: bash

    - name: Convert KMZ to GeoJSON
      run: |
        mkdir -p data
        python convert_kmz_to_geojson.py downloaded_file.kmz data/geojson.json # 转换KMZ到GeoJSON
      shell: bash

    - name: Check for changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/geojson.json
        if git diff --cached --exit-code > /dev/null; then
          echo "No changes detected. Skipping commit." # 没有检测到变化，跳过提交
        else
          git commit -m 'Automated commit of converted GeoJSON' # 提交更改
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub Token进行认证
